apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  labels:
    app: rating-web
    app.kubernetes.io/component: rating-web
    app.kubernetes.io/instance: rating-web
  name: rating-web
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: rating-web:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      uri: https://github.com/zmcdonaldwright/mslearn-aks-workshop-ratings-web
    type: Git
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: node:14-alpine3.15
    type: Docker
  successfulBuildsHistoryLimit: 5
  triggers:
  - github:
      secret: l-xG8tyldDzZNNUJPHFz
    type: GitHub
  - generic:
      secret: wmF-wlhSueghOtOGZxnL
    type: Generic
  - type: ConfigChange
  - imageChange: {}
    type: ImageChange
